kind: pipeline
type: docker
name: consorcio-api-pipeline

# Gatilho: Executa em pushes para a branch 'main' e em qualquer pull request.
trigger:
  branch:
    - main
  event:
    - push
    - pull_request
    - custom

steps:
  # Passo 1: Construir e testar a aplicação Java
  - name: build-and-test
    image: maven:3.8-openjdk-17-slim # Imagem com Maven e Java 17
    commands:
      - mvn clean install
  - name: build-and-publish-image
    image: plugins/docker
    settings:
      registry: docker.io
      # Nome do repositório da imagem. Ex: "username/consorcio-api"
      repo: k3rb3rdock/consorcio-api
      # Tags da imagem. 'latest' e o hash do commit são boas práticas.
      tags:
        - latest
        - ${DRONE_COMMIT_SHA:0:7}
      # Usuário e senha para o registry, configurados como "secrets" no Drone
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    # Este passo só executa em pushes para a branch 'main', e não em pull requests.
    when:
      branch:
        - main
      event:
        - push